-- ============================================================
-- TacticBoard — Seed : Formations complètes
-- Football à 11 (10 formations) + Football à 8 (5 formations)
-- Fiches tactiques rédigées au niveau analyste professionnel
-- ============================================================

-- Truncate to allow re-seeding
TRUNCATE TABLE formations RESTART IDENTITY CASCADE;

-- ============================================================
-- FOOTBALL À 11
-- ============================================================

-- ─── 1. 4-3-3 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-3-3',
  '11',
  'Le 4-3-3 est l''une des formations les plus polyvalentes et offensivement ambitieuses du football moderne. Popularisé par l''Ajax d''Amsterdam dans les années 1970 puis perfectionné par la génération de Guardiola au Barça, ce système repose sur un triptyque offensif dévastateur combiné à un entrejeu dynamique capable de récupérer et de distribuer rapidement. La formation privilégie le pressing haut, la conservation du ballon et la verticalité dans les transitions.',
  'Le 4-3-3 fonctionne comme un organisme collectif où chaque ligne doit se coordonner parfaitement. En phase de possession, l''équipe cherche à créer une supériorité numérique dans le milieu de terrain grâce à des triangles permanents. Le milieu central (numéro 6) sert d''ancre défensive et de pivot de relance, tandis que les deux milieux relayeurs (numéros 8) apportent box-to-box dynamisme et appels entre les lignes. Les ailiers, placés très haut et larges, étirent la défense adverse et cherchent à rentrer dans l''axe sur leur pied dominant pour frapper au but ou jouer une combinaison rapide avec l''attaquant de pointe. Les latéraux ont un rôle crucial : ils montent haut pour créer des surnombres sur les flancs et peuvent même servir d''ailiers supplémentaires quand l''équipe est en possession. Le pressing est organisé par blocs : l''attaquant de pointe déclenche le pressing sur la relance adverse, les ailiers ferment les corridors vers les latéraux, et le milieu de récupération monte pour isoler le porteur du ballon.',
  'Pour attaquer efficacement contre un 4-3-3, l''objectif principal est d''exploiter l''espace laissé dans le dos des latéraux adverses, qui montent fréquemment pour participer à l''animation offensive. La stratégie la plus efficace consiste à jouer avec des ailiers rapides et directs qui se placent dans le couloir opposé au latéral adverse, prêts à recevoir des passes longues diagonales dès que celui-ci monte. Le changement de jeu rapide d''une aile à l''autre, effectué en 2 ou 3 passes maximum, est particulièrement dévastateur car le bloc défensif du 4-3-3 a tendance à se compresser du côté du ballon, laissant l''ailier adverse isolé sur le côté faible. Une deuxième approche consiste à saturer l''axe central en jouant deux attaquants ou un milieu offensif dans le dos du milieu de récupération adverse. Ce joueur clé du 4-3-3, même s''il est protecteur, peut être contourné par des passes en profondeur entre le pivot défensif et les centraux, notamment via un numéro 10 ou un second attaquant mobile. Les transitions rapides après récupération du ballon sont particulièrement dangereuses contre ce système : quand les latéraux et les milieux adverses sont montés, une récupération haute suivie de 2-3 passes directes peut créer des situations de 3 contre 3 ou 3 contre 2 face à la défense.',
  'Défendre contre un 4-3-3 nécessite d''abord de neutraliser les ailiers, points de départ de la quasi-totalité des offensives adverses. La priorité absolue est d''empêcher les ailiers de recevoir dos au but avec de l''espace devant eux : les latéraux doivent les suivre très haut et ne jamais leur laisser de temps pour se retourner. En bloc médian ou bas, il faut absolument fermer l''axe central et réduire les espaces entre les lignes pour empêcher les milieux relayeurs de recevoir entre les lignes. Une option efficace est d''utiliser un milieu en marquage sur le numéro 6 adverse pour priver le 4-3-3 de son pivot de relance. Quand le 4-3-3 perd le ballon, la meilleure réponse est une sortie rapide en profondeur avant que le pressing adverse se réorganise, car les 10-15 secondes suivant une perte de balle par le 4-3-3 sont un moment de vulnérabilité maximale. En set-plays défensifs, la ligne des 4 défenseurs doit rester coordonnée face aux appels croisés des ailiers et de l''avant-centre.',
  '["Pressing haut très efficace avec 3 attaquants", "Domination du milieu de terrain avec 3 joueurs", "Largeur de jeu maximale grâce aux ailiers", "Transition rapide attaque-défense", "Supériorité numérique sur les flancs quand les latéraux montent"]',
  '["Vulnérable aux contre-attaques dans l''espace laissé par les latéraux offensifs", "Le milieu à 3 peut être débordé par un milieu à 4", "Dépend beaucoup de la forme des ailiers", "Exige une condition physique élevée pour presser sur toute la hauteur du terrain", "Risque de déséquilibre défensif si les 8 ne rentrent pas vite"]',
  '["4-5-1", "4-4-2 défensif", "5-3-2"]',
  '{"GK": "Gardien actif dans la relance, capable de jouer au pied et de participer à la construction depuis derrière", "CB": "Défenseur central à l''aise balle au pied, capable de sortir proprement sous le pressing et d''éliminer un joueur par dribble", "LB": "Latéral offensif pur, capable de centrer des deux pieds et de rivaliser en 1v1 défensif malgré ses montées fréquentes", "RB": "Même profil que le latéral gauche : puissance athlétique pour les allers-retours répétés sur tout le couloir", "CDM": "Milieu de récupération, excellent dans les duels, intelligence de positionnement pour couvrir les espaces laissés par les 8", "CM-L": "Milieu relayeur box-to-box, percutant, capable de finir et de défendre haut", "CM-R": "Milieu relayeur box-to-box avec vision de jeu longue pour alimenter les ailiers", "LW": "Ailier gauche rentrant sur le pied droit, frappe de loin, dribble en 1v1", "RW": "Ailier droit rentrant sur le pied gauche, vitesse de pointe et percussion", "ST": "Avant-centre pivot capable de combiner, d''éliminer et de finir de la tête comme du pied"}',
  '["FC Barcelone (Guardiola, 2008-2012)", "Liverpool (Klopp, 2017-2024)", "Borussia Dortmund (Klopp, 2011-2015)", "Bayern Munich (Heynckes/Flick)", "Équipe de France (Deschamps, 2018-2021)"]',
  '{"attack": 82, "defense": 62, "pressing": 88, "possession": 78, "transition": 80}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.78},{"id":"CB-R","label":"DC","x":0.65,"y":0.83},{"id":"CB-L","label":"DC","x":0.35,"y":0.83},{"id":"LB","label":"DG","x":0.18,"y":0.78},{"id":"CDM","label":"MDC","x":0.5,"y":0.65},{"id":"CM-R","label":"MR","x":0.68,"y":0.55},{"id":"CM-L","label":"ML","x":0.32,"y":0.55},{"id":"RW","label":"AD","x":0.82,"y":0.32},{"id":"LW","label":"AG","x":0.18,"y":0.32},{"id":"ST","label":"BU","x":0.5,"y":0.18}]'
);

-- ─── 2. 4-4-2 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-4-2',
  '11',
  'Le 4-4-2 classique est la formation fondatrice du football anglais et l''une des plus équilibrées de l''histoire. Il repose sur deux blocs solides de quatre joueurs qui forment deux lignes compactes très difficiles à pénétrer. Ce système est idéal pour des équipes qui misent sur la solidité défensive, la discipline collective et les transitions rapides exploitant le duo d''attaquants. Sa lisibilité et sa robustesse en font une référence tactique intemporelle.',
  'Le 4-4-2 fonctionne sur deux principes fondamentaux : la compacité défensive et l''efficacité offensive. En phase de possession, les deux milieux centraux construisent le jeu avec une répartition claire des rôles — l''un plus défensif (qui couvre) et l''autre plus offensif (qui cherche à jouer entre les lignes ou arriver en soutien des attaquants). Les milieux latéraux courent les couloirs de bout en bout et fournissent des ballons aux deux attaquants dont la complémentarité est la clé du système : idéalement, un attaquant de fixation qui joue dos au but et un attaquant mobile qui se projette dans la profondeur. Le jeu en dehors, avec des centres et des remises en première touche, est l''arme principale. En phase défensive, le bloc de 8 (4+4) se forme immédiatement et réduit l''espace central en priorité.',
  'Le 4-4-2 classique présente une faille structurelle importante : l''espace entre la ligne des 4 milieux et la ligne des 4 défenseurs, appelé "l''entre-deux". Un numéro 10 ou un milieu offensif qui aime se positionner dans cet espace peut faire des dégâts considérables. La stratégie la plus efficace est d''utiliser un meneur de jeu capable de recevoir entre les lignes, de se retourner rapidement et de servir les attaquants ou de frapper. Une autre faiblesse est la zone au milieu de terrain : avec seulement 2 milieux centraux, créer une supériorité numérique à 3v2 dans l''axe crée des espaces pour jouer en triangle. Les largeurs sont également importantes : les milieux latéraux du 4-4-2 doivent défendre et attaquer, ce qui les fatigue. En fin de match ou après des courses intensives, les espaces derrière eux sur les flancs peuvent être exploités par des ailiers rapides.',
  'Le 4-4-2 est une formation naturellement solide qui se défend de lui-même grâce à sa double ligne compacte. Pour défendre face aux attaques adverses, la priorité est de maintenir le bloc compact et de ne jamais laisser de joueur adverse recevoir librement entre les lignes. Les milieux centraux doivent se parler constamment pour gérer les rotations quand l''adversaire surcharge un côté. Le piège classique à éviter : les milieux latéraux qui montent trop haut et reviennent en retard, laissant les défenseurs en infériorité. La meilleure défense du 4-4-2 reste son organisation collective : si les deux lignes restent à moins de 30-35 mètres l''une de l''autre, l''équipe adverse aura très peu d''espaces pour construire.',
  '["Solidité défensive remarquable grâce au double bloc", "Duo d''attaquants complémentaires très polyvalent", "Clarté des rôles — chaque joueur sait exactement ce qu''il doit faire", "Excellentes transitions rapides en contre-attaque", "Formation idéale pour les équipes moins techniques qui veulent être compactes"]',
  '["L''espace entre les deux lignes exploitable par un n°10", "Infériorité numérique au milieu face à un trio défensif (4-3-3, 4-2-3-1)", "Les milieux latéraux doivent énormément courir sur toute la longueur du terrain", "Manque de créativité si les deux milieux centraux sont trop défensifs", "Dépendance forte aux performances des deux attaquants"]',
  '["4-2-3-1", "4-3-3", "3-5-2"]',
  '{"GK": "Gardien communicatif qui organise la défense", "CB": "Défenseur central fort dans les duels aériens et au sol, solide dans les 1v1", "LB": "Latéral polyvalent capable de défendre et de monter pour centrer", "RB": "Même profil, plus offensif si le milieu droit est plus défensif", "CM-D": "Milieu défensif : récupérateur, couverture de l''espace, relance simple", "CM-O": "Milieu offensif : vision, passes décisives, arrivées dans la surface", "ML": "Milieu gauche : travailleur, capable de centrer et de défendre en 1v1", "MR": "Milieu droit : idem, souvent plus offensif pour créer des décalages", "ST-1": "Attaquant de fixation : fort physiquement, jeu de dos, remises pour le partenaire", "ST-2": "Attaquant mobile : vitesse, appels dans la profondeur, finition"}',
  '["AC Milan (Sacchi, 1988-1994)", "Manchester United (Ferguson, 1993-2013)", "Leicester City (Ranieri, 2015-2016)", "Chelsea (Mourinho, 2004-2006)", "Équipe de France (1998, Jacquet)"]',
  '{"attack": 70, "defense": 78, "pressing": 62, "possession": 65, "transition": 75}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.78},{"id":"CB-R","label":"DC","x":0.65,"y":0.83},{"id":"CB-L","label":"DC","x":0.35,"y":0.83},{"id":"LB","label":"DG","x":0.18,"y":0.78},{"id":"MR","label":"MR","x":0.82,"y":0.58},{"id":"CM-D","label":"MC","x":0.62,"y":0.62},{"id":"CM-O","label":"MC","x":0.38,"y":0.62},{"id":"ML","label":"MG","x":0.18,"y":0.58},{"id":"ST-R","label":"BU","x":0.62,"y":0.22},{"id":"ST-L","label":"BU","x":0.38,"y":0.22}]'
);

-- ─── 3. 4-2-3-1 ─────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-2-3-1',
  '11',
  'Le 4-2-3-1 est la formation la plus répandue dans le football professionnel européen des années 2010-2020. Elle marie solidité défensive et créativité offensive grâce à un double pivot protecteur qui libère le trident offensif (meneur + ailiers). L''équilibre entre lignes en fait un choix privilégié des entraîneurs pragmatiques cherchant à ne pas prendre de risques en défense tout en ayant les ressources pour créer le déséquilibre vers l''avant.',
  'Le 4-2-3-1 s''articule autour du double pivot, colonne vertébrale du système. Ces deux milieux défensifs jouent en décalage : l''un sort pour presser ou dérober le ballon pendant que l''autre couvre l''espace laissé libre. Au-dessus d''eux, le meneur de jeu (n°10) est le chef d''orchestre : il reçoit entre les lignes, distribue aux ailiers, arrive en soutien de l''avant-centre ou déclenche lui-même. Les ailiers jouent très hauts et larges, tirent les latéraux adverses dans leurs couloirs pour créer des espaces dans l''axe. L''avant-centre — souvent un pivot de qualité — joue des remises et des déviations pour le meneur ou les milieux qui arrivent en soutien. En phase défensive, le 4-2-3-1 forme rapidement un bloc 4-4-2 (meneur + un attaquant, les ailiers devenant milieux latéraux) ou un 4-5-1 (les trois offensifs rejoignent les deux pivots).',
  'La clé pour attaquer contre un 4-2-3-1 est de trouver les espaces entre les couloirs de chaque côté du double pivot. Quand les deux pivots s''attirent vers le même côté, un écart se crée de l''autre côté de l''axe, exploitable par un milieu arrivant en retard ou par une combinaison rapide avec un ailier rentrant. Une autre stratégie gagnante est d''utiliser les largeurs : les ailiers adverses en 4-2-3-1 défendent souvent mal car ils sont positionnés très haut. Si on tire parti des flancs avec des latéraux offensifs qui centrent tôt et des attaquants capables d''attaquer les premiers ballons, le système montre ses limites. Enfin, une pression collective sur le double pivot peut être décisive : si les deux pivots sont perturbés dans leurs distributions, le 4-2-3-1 perd son équilibre et le meneur se retrouve isolé sans relais.',
  'Défendre contre le 4-2-3-1 nécessite de neutraliser le meneur de jeu, pivot de toutes les offensives. Il faut désigner un joueur pour lui coller dessus en permanence — soit un milieu défensif, soit une organisation collective qui l''empêche de se retourner. La deuxième priorité est de ne pas permettre aux ailiers de couper vers l''intérieur : les latéraux doivent les pousser vers la ligne de touche où ils sont moins dangereux. En phase de pression, il faut attaquer le double pivot vite avant qu''ils ne puissent se retourner : si on isole un pivot, il sera souvent en difficulté pour se sortir des pressing intenses. Créer un 3v2 dans l''axe en montant un milieu supplémentaire peut perturber toute l''organisation du 4-2-3-1.',
  '["Double pivot très sécurisant défensivement", "Le n°10 bénéficie de liberté totale pour créer", "Excellente couverture du terrain sur toute la largeur", "Très bonne gestion des transitions défensives", "Polyvalence : peut évoluer en 4-4-2 ou 4-5-1 défensif rapidement"]',
  '["Dépendance au n°10 — s''il est neutralisé, l''équipe perd son créateur", "Les ailiers doivent revenir défendre, ce qui limite leur impact offensif", "Le double pivot peut manquer de créativité et ralentir le jeu", "Avant-centre souvent isolé s''il n''est pas servi rapidement", "Moins efficace en possession pure face à une équipe qui presse haut"]',
  '["4-3-3 (pressing haut)", "3-5-2", "4-1-4-1"]',
  '{"GK": "Gardien organisateur, à l''aise pour relancer avec les pieds", "CB": "Défenseur central technique, capable de sortir proprement sous le pressing", "LB": "Latéral offensif avec bonne qualité de centre pour alimenter les ailiers", "RB": "Latéral droit dynamique qui monte en soutien de l''ailier", "CDM-1": "Premier pivot : récupérateur-destructor, duels, intervention pour protéger la défense", "CDM-2": "Deuxième pivot : meilleur techniquement, relance proprement et distribue", "CAM": "Meneur de jeu : le joueur le plus créatif, vision, dribble, passes décisives", "LW": "Ailier gauche : vitesse, percussion, rentrant", "RW": "Ailier droit : profil miroir, rentre sur le pied gauche", "ST": "Avant-centre : pivot ou mobile, charnière de toutes les combinaisons"}',
  '["Real Madrid (Ancelotti, 2003-2006)", "Allemagne (Löw, 2010-2014)", "Chelsea (Mourinho, 2006-2007)", "Atletico Madrid (Simeone)", "Manchester City (pré-Guardiola)"]',
  '{"attack": 76, "defense": 72, "pressing": 68, "possession": 80, "transition": 65}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.78},{"id":"CB-R","label":"DC","x":0.65,"y":0.83},{"id":"CB-L","label":"DC","x":0.35,"y":0.83},{"id":"LB","label":"DG","x":0.18,"y":0.78},{"id":"CDM-R","label":"MDC","x":0.62,"y":0.67},{"id":"CDM-L","label":"MDC","x":0.38,"y":0.67},{"id":"RW","label":"AD","x":0.78,"y":0.45},{"id":"CAM","label":"MO","x":0.5,"y":0.45},{"id":"LW","label":"AG","x":0.22,"y":0.45},{"id":"ST","label":"BU","x":0.5,"y":0.18}]'
);

-- ─── 4. 4-5-1 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-5-1',
  '11',
  'Le 4-5-1 est une formation défensive robuste qui sacrifie la présence offensive en faveur d''une compacité extrême au milieu de terrain. Avec cinq milieux qui forment une ligne hermétique, ce système vise à étouffer l''adversaire dans sa zone de création et à exploiter les espaces en contre-attaque via un avant-centre isolé mais très mobile. C''est la formation des équipes réalistes qui veulent tenir un résultat ou jouer contre des adversaires supérieurs techniquement.',
  'En possession, le 4-5-1 cherche à sortir rapidement de la pression adverse par des passes longues vers l''avant-centre, qui doit avoir les qualités pour garder le ballon, attirer des défenseurs et permettre aux milieux de monter. Une fois la transition effectuée, les ailiers-milieux se projettent vers l''avant pour créer un 4-3-3 ou 4-2-3-1 offensif temporaire. Défensivement, les cinq milieux se resserrent pour former un bloc compact qui couvre tout l''axe central sur une largeur de 40 mètres environ. Les deux milieux latéraux défendent comme des arrières supplémentaires mais doivent être capables de repartir vite vers l''avant pour alimenter le contre.',
  'La clé pour attaquer un 4-5-1 est la patience et la mobilité. La ligne de 5 milieux adverses peut être percée de plusieurs manières. D''abord, en jouant des passes courtes rapides pour forcer des ouvertures dans le bloc compact : quand un joueur adverse sort pour presser, un espace se crée dans son dos. Deuxièmement, les centres depuis les flancs sont très efficaces car les latéraux adverses sont souvent dépassés en profondeur quand les milieux latéraux montent trop haut. La troisième solution est le jeu par-dessus le bloc : des passes lobées vers un attaquant qui court dans le dos des défenseurs peuvent briser le bloc si ceux-ci ne sont pas bien synchronisés. Il faut surtout avoir de la patience et tolérer la possession sans progresser trop tôt.',
  'Le 4-5-1 se défend naturellement bien avec sa ligne de 5. La discipline est le mot-clé : chaque joueur doit rester dans sa zone et ne pas se laisser attirer hors de sa position. Le danger principal est le couloir laissé libre quand un milieu latéral monte trop haut. Si l''équipe adverse récupère le ballon dans ces conditions, elle dispose de 4 contre 3 ou 3 contre 2 en contre-attaque. La ligne de 5 doit donc avoir des règles strictes : dès que la possession est perdue, tout le monde rentre immédiatement. L''avant-centre doit être le premier défenseur sur la relance adverse pour gagner du temps.',
  '["Compacité défensive maximale avec 9 joueurs derrière le ballon", "Contre-attaques dévastatrices si les milieux sont rapides", "Très difficile à percer pour les équipes qui privilégient la possession", "Stabilité défensive qui fatigue les attaquants adverses", "Idéale pour tenir un résultat ou jouer contre des équipes supérieures"]',
  '["Manque flagrant de présence offensive avec un seul attaquant", "L''avant-centre est trop isolé et peut vite se décourager", "Peu de créativité — le jeu peut devenir prévisible défensivement", "Dépend de la qualité et de la vitesse des contre-attaques", "Formation difficile à tenir sur 90 minutes physiquement"]',
  '["4-3-3 (possession)", "3-4-3", "4-4-2"]',
  '{"GK": "Gardien solide dans les 1v1, excellent dans les interventions sur les centres", "CB": "Défenseurs centraux très forts dans les duels, notamment aériens", "LB": "Latéral défensif qui monte peu, priorité à la solidité", "RB": "Idem, discipline et capacité à défendre en 1v1 en priorité", "DM": "Milieu défensif central : pivot protecteur, intercepteur, relance simple", "CM-R": "Milieu droit : box-to-box, défend d''abord mais peut contre-attaquer", "CM-L": "Milieu gauche : idem, avec préférence pour les départs en transition", "ML": "Milieu latéral gauche : ailier défensif, vitesse pour le contre", "MR": "Milieu latéral droit : vitesse, centre, finisseur dans le couloir", "ST": "Avant-centre : forte personnalité, capable de tenir le ballon seul, mobile"}',
  '["Chelsea (Mourinho bloc bas)", "Atletico Madrid (Simeone, variante)", "Grèce (Euro 2004 — Rehhagel)", "Équipe d''Algérie (CAN 2019)", "Leicester défensif (certains matchs)"]',
  '{"attack": 52, "defense": 87, "pressing": 58, "possession": 60, "transition": 72}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.78},{"id":"CB-R","label":"DC","x":0.65,"y":0.83},{"id":"CB-L","label":"DC","x":0.35,"y":0.83},{"id":"LB","label":"DG","x":0.18,"y":0.78},{"id":"MR","label":"MD","x":0.88,"y":0.55},{"id":"CM-R","label":"MC","x":0.68,"y":0.6},{"id":"DM","label":"MDC","x":0.5,"y":0.65},{"id":"CM-L","label":"MC","x":0.32,"y":0.6},{"id":"ML","label":"MG","x":0.12,"y":0.55},{"id":"ST","label":"BU","x":0.5,"y":0.18}]'
);

-- ─── 5. 3-5-2 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '3-5-2',
  '11',
  'Le 3-5-2 est une formation ambitieuse qui tente de cumuler les avantages d''une défense à 3 centraux (solidité dans l''axe) avec la supériorité numérique au milieu de terrain (5 milieux). Les pistons (ou ailiers-milieux) sont au cœur du système : ils jouent à la fois le rôle de latéraux défensifs et d''ailiers offensifs, montant et descendant sans cesse sur toute la longueur du terrain. Ce système exige une discipline tactique et une condition physique exceptionnelles.',
  'En possession, le 3-5-2 cherche à construire proprement depuis les 3 défenseurs centraux qui se dispersent horizontalement pour créer des angles de passe. Les deux milieux défensifs gèrent le tempo et la sécurité pendant que le milieu offensif joue entre les lignes et combine avec les deux attaquants. Le duo d''attaquants fonctionne comme dans un 4-4-2 : un fixateur et un mobile. Les pistons constituent l''arme principale : quand l''adversaire est en place, ils créent des 2v1 sur les flancs avec les attaquants ou les milieux offensifs. En phase défensive, le 3-5-2 se transforme en 5-3-2 avec les pistons qui reculent pour former une ligne de 5.',
  'La faiblesse principale du 3-5-2 sont les espaces derrière les pistons quand ils sont montés haut. Si on récupère le ballon et qu''on joue vite dans le couloir opposé à celui où le piston adverse est monté, on se retrouve dans une situation de 1v1 ou 2v1 favorable face au défenseur central qui doit sortir. Des ailiers rapides qui jouent très larges peuvent étirer les défenseurs centraux et créer des espaces dans l''axe pour un attaquant ou un milieu. Une autre approche efficace est d''exploiter les zones de transition entre le piston adverse et le défenseur central de son côté : ces zones ne sont pas toujours clairement assignées et peuvent créer de la confusion.',
  'Défendre contre un 3-5-2 nécessite d''empêcher les pistons de prendre de la vitesse. Dès que le piston adverse a le ballon dans son couloir, il faut attaquer son couloir extérieur pour l''empêcher de centrer. En retraite défensive, les joueurs les plus proches de la touche adverse doivent harceler les pistons et les empêcher de se retrouver en situations de 1v1 confortables. La zone centrale étant très peuplée avec 5 milieux adverses, la solution est souvent d''étirer le jeu sur les flancs pour créer des espaces par jeu rapide de côté à côté.',
  '["Supériorité numérique garantie au milieu de terrain", "Solidité centrale avec 3 défenseurs centraux", "Les pistons créent une supériorité permanente sur les flancs", "Deux attaquants pour peser sur la défense", "Formation très flexible selon le profil des joueurs"]',
  '["Très exigeant physiquement pour les pistons (90m de course)", "Vulnérable si les pistons sont battus en 1v1 dans leur couloir", "Les défenseurs centraux excentrés doivent couvrir beaucoup d''espace", "Formation complexe à mettre en place tactiquement", "Risque en cas de perte de balle en transition si les pistons sont trop hauts"]',
  '["4-3-3 (largeur)", "4-5-1", "4-4-2"]',
  '{"GK": "Gardien organisateur, communication permanente avec les 3 centraux", "CB-C": "Défenseur central le plus fort dans les duels, libero du système", "CB-R": "Défenseur central droit : couverture de l''espace, remplace le piston en défense", "CB-L": "Défenseur central gauche : idem côté gauche", "WB-R": "Piston droit : le joueur le plus complet du terrain, ailier + latéral", "WB-L": "Piston gauche : même profil, préférence pour la jambe gauche", "CM-D": "Milieu défensif : pivot protecteur des 3 centraux", "CM-O": "Milieu offensif : liant entre la défense et l''attaque", "CAM": "Milieu relayeur : créatif, joue entre les lignes pour les 2 attaquants", "ST-1": "Attaquant de fixation : tient le ballon, aspire les défenseurs", "ST-2": "Attaquant mobile : runs dans la profondeur, finisseur"}',
  '["Juventus (Conte, 2011-2014)", "Inter Milan (Mourinho, 2009-2010)", "Chelsea (Conte, 2016-2018)", "Italie (Mancini, 2020-2021)", "Atlético Madrid (variante)"]',
  '{"attack": 72, "defense": 76, "pressing": 65, "possession": 70, "transition": 70}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DC","x":0.72,"y":0.83},{"id":"CB-C","label":"DC","x":0.5,"y":0.86},{"id":"CB-L","label":"DC","x":0.28,"y":0.83},{"id":"WB-R","label":"PD","x":0.88,"y":0.55},{"id":"CM-D","label":"MDC","x":0.62,"y":0.65},{"id":"CAM","label":"MO","x":0.5,"y":0.52},{"id":"CM-O","label":"MC","x":0.38,"y":0.65},{"id":"WB-L","label":"PG","x":0.12,"y":0.55},{"id":"ST-R","label":"BU","x":0.63,"y":0.22},{"id":"ST-L","label":"BU","x":0.37,"y":0.22}]'
);

-- ─── 6. 3-4-3 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '3-4-3',
  '11',
  'Le 3-4-3 est la formation la plus offensive de l''éventail tactique moderne. Avec trois défenseurs centraux et trois attaquants, elle offre une présence massive dans les deux zones décisives du terrain. Le milieu à 4, souvent composé de deux joueurs centraux et deux pistons, doit assurer la liaison et les transitions à toute vitesse. C''est une formation spectaculaire qui prend des risques calculés pour dominer les adversaires.',
  'En possession, le 3-4-3 cherche à saturer les zones avancées en permanence. Les trois attaquants restent hauts et larges pour créer de l''espace et des courses continues. Les pistons montent pour créer des supériorités sur les flancs, transformant le système en 3-2-5 en possession. Les deux milieux centraux gèrent la transition et ne doivent jamais se retrouver tous les deux au même endroit. En phase défensive, la priorité est une récupération ultra-haute pour ne jamais laisser l''adversaire construire. Si le pressing haut échoue, le 3-4-3 se replie rapidement en 5-4-1 avec les pistons qui défendent.',
  'Pour attaquer contre un 3-4-3, l''espace entre les trois défenseurs est crucial. Quand les pistons montent, des espaces apparaissent entre les centraux excentrés et le piston de leur côté. Un jeu rapide de 2-3 passes peut isoler un attaquant rapide contre un défenseur central en 1v1. Les contre-attaques sont également très efficaces : avec seulement 3 défenseurs et 2 milieux pour couvrir, une récupération haute suivie de transitions rapides crée facilement des situations 3v3 ou 4v3 face à la défense.',
  'Défendre contre un 3-4-3 exige une organisation défensive ultra-rigoureuse. Avec 3 attaquants adverses, chaque défenseur central doit être capable de défendre en 1v1 sans aide. La discipline dans le bloc défensif est primordiale : aucune sortie prématurée des centraux car les 3 attaquants adverses exploiteront immédiatement l''espace créé. En possession, jouer rapidement pour profiter des espaces laissés par les pistons et l''attaque adverse qui ne rentrent pas toujours assez vite.',
  '["Présence offensive maximale avec 3 attaquants permanents", "Pressing ultra-haut qui étouffe les adversaires dans leur zone", "Les pistons créent des supériorités sur les deux flancs simultanément", "Formation spectaculaire qui attire visuellement les espaces", "Excellente pour les équipes dominantes face à des adversaires inférieurs"]',
  '["Défense à 3 très vulnérable aux contre-attaques rapides", "Exige une condition physique et une rigueur tactique exceptionnelles des pistons", "Les deux milieux centraux sont en infériorité face à des milieux à 3 ou 4", "Si les pistons ne rentrent pas, la défense est en 3v3 permanente", "Formation difficile à maintenir sur 90 minutes contre des équipes bien organisées"]',
  '["4-5-1 défensif", "5-3-2", "4-4-2 compact"]',
  '{"GK": "Gardien très actif dans la construction, must jouer au pied", "CB-R": "Défenseur central droit : doit défendre en 1v1 régulièrement", "CB-C": "Libero central : le plus expérimenté, leader défensif", "CB-L": "Défenseur central gauche : couverture de l''ailier adverse", "WB-R": "Piston droit : le joueur le plus important du système — ailier + latéral", "WB-L": "Piston gauche : même exigence, qualité technique et athlétique de pointe", "CM-1": "Milieu central défensif : récupérateur qui filtre les transitions", "CM-2": "Milieu central offensif : liaison et créativité vers l''attaque", "RW": "Ailier droit : vitesse, dribble, finition, reste très haut", "LW": "Ailier gauche : miroir du droit, percussion", "ST": "Avant-centre : pivot de tout le système offensif, combine, finit"}',
  '["Chelsea (Tuchel, 2021)", "Manchester City (variante)", "Ajax (pré-Champions League)", "Belgique (Martinez)", "AS Roma (Mourinho, variante)"]',
  '{"attack": 88, "defense": 55, "pressing": 82, "possession": 68, "transition": 84}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DC","x":0.72,"y":0.83},{"id":"CB-C","label":"DC","x":0.5,"y":0.86},{"id":"CB-L","label":"DC","x":0.28,"y":0.83},{"id":"WB-R","label":"PD","x":0.88,"y":0.58},{"id":"CM-1","label":"MC","x":0.62,"y":0.62},{"id":"CM-2","label":"MC","x":0.38,"y":0.62},{"id":"WB-L","label":"PG","x":0.12,"y":0.58},{"id":"RW","label":"AD","x":0.78,"y":0.28},{"id":"ST","label":"BU","x":0.5,"y":0.18},{"id":"LW","label":"AG","x":0.22,"y":0.28}]'
);

-- ─── 7. 5-3-2 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '5-3-2',
  '11',
  'Le 5-3-2 est la référence des formations défensives solides qui gardent les armes pour blesser en contre-attaque. Avec cinq défenseurs qui forment un mur hermétique dans leur zone, cette formation vise à annihiler tout danger dans la moitié de terrain défensive avant d''exploiter les espaces en contre avec un duo d''attaquants complémentaires. C''est le choix des équipes pragmatiques qui veulent sécuriser le résultat ou affronter des adversaires favoris.',
  'En phase défensive (prioritaire), les cinq défenseurs forment une ligne compacte et basse. Les deux pistons défendent à hauteur des latéraux, rendant la ligne de 5 très difficile à pénétrer de face. Le milieu de 3 se place devant la défense pour filtrer les passes et presser les milieux adverses. En possession, les pistons se transforment en ailiers et montent pour créer des situations 3v4 ou 4v4 en attaque. Le duo d''attaquants joue des combinaisons courtes en attendant que les pistons rejoignent l''attaque pour créer une supériorité numérique.',
  'La ligne de 5 du 5-3-2 semble imperméable, mais elle possède des failles exploitables. La première est le jeu entre la ligne de 5 défenseurs et le milieu de 3 : cet espace entre les deux lignes peut être occupé par un numéro 10 ou un milieu offensif qui reçoit librement. Une deuxième approche est de saturer les flancs : si on envoie deux attaquants sur le même piston adverse, il est en surcharge et doit choisir entre défendre le fond et laisser le centre libre. Les phases arrêtées (corners, coups francs) sont également très efficaces face à une équipe qui se concentre sur son organisation en mouvement.',
  'Avec 5 défenseurs, le 5-3-2 se défend de lui-même dans l''axe. Le danger vient des flancs et des espaces entre les lignes. Si l''adversaire cherche à jouer par-dessus le bloc avec des passes longues, les défenseurs centraux doivent être très forts dans les duels aériens. La communication entre les 5 défenseurs est primordiale pour éviter les sorties prématurées et les espaces dans la ligne.',
  '["Solidité défensive maximale — très difficile à percer de face", "5 joueurs en défense = protection contre les centres et les attaques de couloir", "Contre-attaques efficaces avec les pistons qui partent vite", "Formation idéale pour défendre un résultat en fin de match", "Psychologiquement rassurante pour les défenseurs"]',
  '["Manque de présence offensive — 2 attaquants peuvent être isolés", "Les 3 milieux sont en infériorité numérique face à des milieux à 4", "Peu de pressing : l''adversaire peut construire tranquillement", "Dépend beaucoup des performances des pistons à monter et descendre", "Formation prévisible défensivement"]',
  '["4-3-3 (possession)", "4-4-2 (transitions)", "3-4-3"]',
  '{"GK": "Gardien de haut niveau : distribution précise pour lancer les contre-attaques", "CB-C": "Défenseur central : libero du système, leader vocal et tactique", "CB-R": "Défenseur central droit : fort en 1v1 et dans les airs", "CB-L": "Défenseur central gauche : idem côté gauche", "WB-R": "Piston droit : athlète complet, défend comme un latéral, attaque comme un ailier", "WB-L": "Piston gauche : miroir du droit", "DM": "Milieu défensif : récupérateur qui couvre la défense à 5", "CM-1": "Milieu central : la box-to-box, lien entre défense et attaque", "CM-2": "Milieu offensif : créativité pour alimenter le duo d''attaquants", "ST-1": "Attaquant principal : finisseur, disponible pour les contre-attaques", "ST-2": "Second attaquant : mobile, capacité à tenir le ballon seul"}',
  '["Inter Milan (Benitez)", "Portugal (Euro 2016)", "Atlético Madrid (format défensif)", "Équipe de Simeone en phase de résultat", "Certaines équipes de Serie A italienne"]',
  '{"attack": 62, "defense": 90, "pressing": 48, "possession": 55, "transition": 68}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"WB-R","label":"PD","x":0.88,"y":0.75},{"id":"CB-R","label":"DC","x":0.68,"y":0.82},{"id":"CB-C","label":"DC","x":0.5,"y":0.85},{"id":"CB-L","label":"DC","x":0.32,"y":0.82},{"id":"WB-L","label":"PG","x":0.12,"y":0.75},{"id":"CM-R","label":"MC","x":0.68,"y":0.6},{"id":"DM","label":"MDC","x":0.5,"y":0.65},{"id":"CM-L","label":"MC","x":0.32,"y":0.6},{"id":"ST-R","label":"BU","x":0.62,"y":0.22},{"id":"ST-L","label":"BU","x":0.38,"y":0.22}]'
);

-- ─── 8. 5-4-1 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '5-4-1',
  '11',
  'Le 5-4-1 est la formation la plus défensive possible dans un système à 11 joueurs. Avec 9 joueurs systématiquement derrière le ballon, elle vise la solidité absolue et l''invulnérabilité dans la zone défensive. Elle est utilisée pour tenir un résultat, jouer des matchs retour après une victoire, ou affronter des équipes nettement supérieures. Son efficacité repose sur une discipline collective sans faille et un avant-centre courageux.',
  'Le 5-4-1 n''a pas vraiment de phase offensive structurée : il attend la récupération du ballon et cherche à sortir proprement pour permettre à l''avant-centre de créer quelque chose seul ou avec les milieux latéraux qui montent prudemment. En défense, le bloc de 4 milieux et 5 défenseurs forme un carré de 9 joueurs sur 30 mètres qui ne laisse aucun espace. La priorité absolue est de ne jamais permettre une frappe sans opposition dans la surface. L''avant-centre doit déclencher la pression sur la relance adverse pour ralentir l''avancée et donner le temps au bloc de s''organiser.',
  'Le 5-4-1 est extrêmement difficile à percer de manière frontale. La solution est de faire circuler le ballon rapidement pour fatiguer le bloc et trouver les rares espaces disponibles. Les changements de jeu rapides d''une aile à l''autre peuvent désorganiser une ligne de 9 qui peine à se déplacer collectivement à grande vitesse. Les situations de phase fixe (corners, coups francs) sont particulièrement efficaces car le 5-4-1 se concentre sur l''organisation dynamique et peut être pris par surprise sur des schémas élaborés. La répétition de tirs de l''extérieur de la surface peut également forcer des erreurs.',
  'La formation se défend d''elle-même. La discipline est le mot d''ordre : 9 joueurs derrière le ballon signifie aucune tentation d''aller chercher le duel ailleurs que dans la zone défensive. Les risques principaux sont les phases arrêtées adverses et la fatigue en fin de match qui peut créer des trous dans le bloc. Un seul but encaissé peut briser psychologiquement la formation.',
  '["Solidité défensive quasi absolue sur 90 minutes", "Très difficile à battre pour toute équipe, même supérieure", "Conservation d''énergie en défense profonde", "Idéal pour les matchs retour ou pour tenir un résultat mince", "Peu de risques de concéder des buts sur le jeu"]',
  '["Quasi aucune capacité offensive — dépend uniquement des coups de pied arrêtés ou erreurs adverses", "L''avant-centre est totalement isolé et peut décrocher mentalement", "Formation moralement difficile à maintenir pour les joueurs offensifs", "Si un but est concédé, l''équipe doit sortir et se retrouve exposée", "Faible pour le moral et l''attractivité du jeu"]',
  '["4-3-3 (possession prolongée)", "3-4-3", "4-4-2"]',
  '{"GK": "Gardien de sang-froid, excellent réflexe, leader vocal de la défense", "CB-C": "Libero : le patron de la défense, organisateur permanent", "CB-R/L": "Défenseurs centraux latéraux : forts en 1v1, sans prise de risque", "WB-R/L": "Pistons : défendent comme des latéraux, montent rarement", "MR/ML": "Milieux latéraux : courent tout le match pour bloquer les couloirs", "CM-R/L": "Milieux centraux : récupérateurs, relance simple et directe", "ST": "Avant-centre guerrier : courage, ténacité, capable de tenir le ballon seul sur de longues périodes"}',
  '["Équipes en déplacement contre le top 6", "Leicester sur de grands matchs", "Grèce (Euro 2004 en finale)", "Atlético Madrid dans certains matchs de C1 en déplacement", "Équipes promues jouant le maintien"]',
  '{"attack": 48, "defense": 95, "pressing": 42, "possession": 50, "transition": 58}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"WB-R","label":"PD","x":0.88,"y":0.75},{"id":"CB-R","label":"DC","x":0.68,"y":0.82},{"id":"CB-C","label":"DC","x":0.5,"y":0.85},{"id":"CB-L","label":"DC","x":0.32,"y":0.82},{"id":"WB-L","label":"PG","x":0.12,"y":0.75},{"id":"MR","label":"MD","x":0.78,"y":0.58},{"id":"CM-R","label":"MC","x":0.62,"y":0.62},{"id":"CM-L","label":"MC","x":0.38,"y":0.62},{"id":"ML","label":"MG","x":0.22,"y":0.58},{"id":"ST","label":"BU","x":0.5,"y":0.2}]'
);

-- ─── 9. 4-1-4-1 ─────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-1-4-1',
  '11',
  'Le 4-1-4-1 est une variante du 4-4-2 et du 4-5-1 qui place un seul milieu défensif devant la défense pour protéger l''axe central. La ligne de 4 milieux est très haute et proactive en possession, créant un système hybride capable de basculer entre une défense solide et une attaque organisée selon l''état du match. Le pivot défensif est la pièce maîtresse de ce système.',
  'Le milieu défensif isolé est le véritable chef d''orchestre du 4-1-4-1. Il doit être capable de récupérer les ballons perdus par la ligne de 4 milieux qui joue haut, de distribuer proprement vers les milieux offensifs et de couvrir les espaces laissés par les latéraux qui montent. La ligne de 4 milieux joue très haut et crée des situations de 4v4 ou 4v3 dans la zone de création adverse. L''avant-centre travaille entre les lignes ou en profondeur selon le profil. En phase défensive, les 4 milieux reculent pour former un bloc 4-4-1-1 ou 4-5-1 avec le seul pivot devant.',
  'La faiblesse du 4-1-4-1 est l''espace laissé entre le pivot et les 4 milieux quand ces derniers montent. Un numéro 10 ou un milieu relayeur qui arrive dans cet espace peut recevoir sans opposition et créer immédiatement le danger. Pour exploiter cela, il faut un joueur capable de courir dans l''espace entre les lignes et de tourner rapidement. Les centrales adverses sont aussi exploitables si le pivot adverse est isolé : une surcharge 2v1 sur lui peut le forcer à laisser passer le ballon.',
  'En défense contre ce système, il faut identifier rapidement quand la ligne de 4 milieux monte trop haut et exploiter ces moments de transition. La récupération du ballon dans la moitié adverse doit être suivie d''un jeu direct en profondeur avant que la ligne ne revienne. Le pivot adverse peut être contourné par des passes lobées légèrement devant lui.',
  '["Protection de l''axe défensif excellente grâce au pivot isolé", "La ligne de 4 milieux haute crée de nombreuses occasions", "Excellent pressing collectif organisé sur deux lignes", "Flexibilité pour basculer entre différents états du match", "Efficace pour contrôler le milieu de terrain face à des 4-4-2"]',
  '["Le pivot seul peut être surchargé en 2v1", "Espace entre le pivot et la ligne de 4 milieux exploitable", "Moins créatif offensivement que le 4-2-3-1", "L''avant-centre peut être isolé si la transition n''est pas rapide", "Exige un pivot de classe mondiale pour fonctionner au top niveau"]',
  '["4-3-3", "3-5-2", "4-2-3-1"]',
  '{"GK": "Gardien actif dans la relance pour le pivot", "CB": "Défenseurs centraux solides qui couvrent le pivot en cas de dépassement", "LB": "Latéral offensif : monte régulièrement pour créer des surnombres", "RB": "Idem côté droit", "CDM": "LE pivot — le joueur le plus important : technique, puissance, vision, duels", "CM-L": "Milieu gauche : box-to-box, travail défensif et offensif", "CM-R": "Milieu droit : idem", "ML": "Milieu latéral gauche : créativité, centres, finition", "MR": "Milieu latéral droit : percussion et profondeur", "ST": "Avant-centre : profil complet pour jouer seul en pointe"}',
  '["Arsenal (Wenger, variante)", "France (Zidane era)", "Espagne (possessionnel)", "Liverpool (époque Benitez)", "AC Milan (années 2000)"]',
  '{"attack": 62, "defense": 78, "pressing": 72, "possession": 76, "transition": 62}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.78},{"id":"CB-R","label":"DC","x":0.65,"y":0.83},{"id":"CB-L","label":"DC","x":0.35,"y":0.83},{"id":"LB","label":"DG","x":0.18,"y":0.78},{"id":"CDM","label":"MDC","x":0.5,"y":0.68},{"id":"MR","label":"MD","x":0.78,"y":0.52},{"id":"CM-R","label":"MC","x":0.62,"y":0.56},{"id":"CM-L","label":"MC","x":0.38,"y":0.56},{"id":"ML","label":"MG","x":0.22,"y":0.52},{"id":"ST","label":"BU","x":0.5,"y":0.18}]'
);

-- ─── 10. 4-3-3 Pressing Haut ────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-3-3 Pressing',
  '11',
  'Le 4-3-3 Pressing Haut, popularisé par Jürgen Klopp à Dortmund et Liverpool, pousse le principe du pressing à son paroxysme. L''équipe défend dans la moitié adverse, avec le trio offensif qui déclenche l''intense pression sur la relance adversaire dès la récupération du gardien. L''objectif est de forcer des erreurs dans les zones avancées et de transformer chaque perte de balle adverse en occasion de but immédiate. Cette "gegenpressing" (contre-pressing instantané) est l''un des systèmes les plus électriques et spectaculaires du football contemporain.',
  'Le pressing haut n''est pas seulement une phase défensive — c''est un mode d''attaque à part entière. Dès que l''adversaire a le ballon dans sa moitié de terrain, l''attaquant de pointe déclenche la pression en coupant les options de passe du gardien ou du défenseur central, forçant un long dégagement. Les ailiers harcèlent les défenseurs centraux latéraux tandis que les milieux relayeurs pressent les milieux adverses. L''objectif est de récupérer le ballon dans une zone avancée, à 30-40 mètres du but adverse. Une fois la récupération effectuée, la transition est immédiate : passe directe vers un attaquant qui reçoit dans une situation avantageuse face au but. Toute l''équipe doit être synchronisée car un pressing raté laisse un espace énorme dans le dos de la ligne haute.',
  'Le talon d''Achille du 4-3-3 pressing haut est le jeu long. Si l''adversaire arrive à passer au-dessus du pressing (par des passes longues lobées vers un attaquant rapide ou un milieu), l''espace laissé dans le dos de la défense haute est immense. Un attaquant de vitesse, un milieu qui fait une course en profondeur au moment du pressing ou un changement de jeu rapide peut instantanément placer l''équipe qui presse en situation de danger. Pour maximiser cette stratégie, il faut un avant-centre très véloce capable de courir dans le dos des 4 défenseurs adverses qui restent haut. Les équipes qui maîtrisent les passes longues précises et rapides vers un cible en profondeur font systématiquement souffrir le pressing haut.',
  'Défendre contre le pressing haut du 4-3-3 est un défi technique autant que mental. La solution principale est la qualité de la relance sous pression : les défenseurs doivent être capables de jouer vite et précisément quand ils sont pressés. Un gardien qui joue au pied est indispensable car il peut souvent trouver un joueur libre qui échappe au pressing. La deuxième solution est le jeu long maîtrisé : un défenseur central qui envoie un long ballon précis vers un attaquant de grande taille ou vers un ailier rapide peut neutraliser tout le pressing en une touche. Les pressing traps (fausses sorties pour attirer le presseur puis jouer dans l''espace) sont également très efficaces.',
  '["Récupération haute du ballon → occasions immédiates de but", "Pression psychologique permanente sur la défense adverse", "Football spectaculaire et intense qui démoralise les adversaires", "Transitions ultra-rapides qui ne laissent pas le temps à l''adversaire de s''organiser", "Idéal pour les équipes avec des joueurs très athlétiques et polyvalents"]',
  '["Exige une condition physique de très haut niveau (10-12 km par match)", "Si un pressing raté, l''équipe est exposée à des contre-attaques dévastatrices", "Difficile à maintenir sur 90 minutes — s''épuise en fin de match", "Vulnérable aux équipes qui maîtrisent le jeu long précis", "Exige une synchronisation parfaite — une erreur peut coûter cher"]',
  '["5-4-1 (bloc bas)", "4-5-1 défensif", "3-5-2 (transition rapide)"]',
  '{"GK": "Gardien très actif au pied, participe à la relance et déclenche les contre-pressing", "CB": "Défenseurs centraux très hauts : défense en 1v1 obligatoire, excellente vitesse", "LB": "Latéral gauche : monte jusqu''à la mi-terrain pour presser les latéraux adverses", "RB": "Idem côté droit", "CDM": "Milieu récupérateur : déclenche le contre-pressing immédiatement à chaque perte de balle", "CM-L": "Milieu relayeur : 12+ km par match, presse et attaque alternativement", "CM-R": "Idem côté droit", "LW": "Ailier gauche : premier presseur sur le défenseur central adverse droit", "RW": "Ailier droit : premier presseur sur le défenseur central adverse gauche", "ST": "Avant-centre : déclencheur du pressing sur le gardien ou le défenseur central le plus haut"}',
  '["Liverpool (Klopp, 2015-2024)", "Borussia Dortmund (Klopp, 2008-2015)", "RB Leipzig (Nagelsmann)", "Brighton (De Zerbi)", "Bayer Leverkusen (Xabi Alonso)"]',
  '{"attack": 85, "defense": 60, "pressing": 96, "possession": 70, "transition": 88}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"RB","label":"DD","x":0.82,"y":0.75},{"id":"CB-R","label":"DC","x":0.64,"y":0.8},{"id":"CB-L","label":"DC","x":0.36,"y":0.8},{"id":"LB","label":"DG","x":0.18,"y":0.75},{"id":"CDM","label":"MDC","x":0.5,"y":0.62},{"id":"CM-R","label":"MR","x":0.68,"y":0.52},{"id":"CM-L","label":"ML","x":0.32,"y":0.52},{"id":"RW","label":"AD","x":0.82,"y":0.28},{"id":"LW","label":"AG","x":0.18,"y":0.28},{"id":"ST","label":"BU","x":0.5,"y":0.15}]'
);

-- ============================================================
-- FOOTBALL À 8
-- ============================================================

-- ─── 11. 3-3-1 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '3-3-1',
  '8',
  'Le 3-3-1 est la formation la plus équilibrée du football à 8. Avec 3 défenseurs, 3 milieux et 1 attaquant, elle offre une couverture défensive solide tout en maintenant une présence offensive via un attaquant de pointe soutenu par le milieu. Idéale pour les équipes jeunes qui apprennent les principes tactiques, c''est une formation pédagogique qui enseigne les concepts fondamentaux du positionnement et de la compacité.',
  'En possession, les 3 milieux jouent en triangle pour créer des angles de passe permanents. Le milieu central gère la construction et la transition pendant que les deux milieux latéraux cherchent à déborder et centrer pour l''attaquant. Les 3 défenseurs restent groupés pour protéger le gardien, le central servant parfois de libero qui relance proprement. L''attaquant de pointe joue haut et cherche à provoquer les défenseurs adverses pour créer des espaces pour les milieux.',
  'Pour attaquer un 3-3-1, les espaces sur les flancs sont prioritaires. Avec 3 défenseurs qui ne peuvent pas tous les deux couvrir les couloirs, un milieu latéral rapide qui déborde crée immédiatement un 1v1 ou 2v1 dans le couloir. Les passes en profondeur entre les défenseurs centraux et latéraux adverses sont également très efficaces si l''attaquant fait un appel bien chronométré.',
  'La ligne de 3 défenseurs du 3-3-1 est relativement solide mais vulnérable si les milieux ne reviennent pas. La discipline des milieux est clé : dès que l''équipe perd le ballon, au moins un milieu doit redescendre pour aider les défenseurs et éviter les situations de 2v3 défensives.',
  '["Formation pédagogique idéale pour les jeunes joueurs", "Équilibre offensif-défensif raisonnable", "Le triangle de milieux crée de la fluidité dans la circulation", "Compacité naturelle avec les deux blocs proches", "Adaptable selon les profils des joueurs disponibles"]',
  '["Un seul attaquant peut être isolé et découragé", "Les flancs sont souvent peu couverts en défense", "Manque de puissance offensive face à des équipes à 2 attaquants", "Les milieux latéraux doivent courir beaucoup pour couvrir tout le terrain", "Peu de créativité si le milieu central n''est pas de qualité"]',
  '["3-2-2", "2-3-2", "4-2-1"]',
  '{"GK": "Gardien actif, communique avec les 3 défenseurs", "CB-C": "Défenseur central : leader défensif, relance proprement", "CB-R": "Défenseur droit : défend le couloir droit", "CB-L": "Défenseur gauche : idem côté gauche", "CM": "Milieu central : pivot du jeu, récupérateur et distributeur", "ML": "Milieu gauche : latéral offensif potentiel", "MR": "Milieu droit : offensif quand l''équipe est en possession", "ST": "Attaquant : mobilité, dribble, finition — doit tout faire seul"}',
  '["Catégories U11-U13 en France", "Équipes débutantes", "Clubs formateurs avec peu d''effectif"]',
  '{"attack": 72, "defense": 70, "pressing": 65, "possession": 68, "transition": 72}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DD","x":0.75,"y":0.8},{"id":"CB-C","label":"DC","x":0.5,"y":0.84},{"id":"CB-L","label":"DG","x":0.25,"y":0.8},{"id":"MR","label":"MD","x":0.75,"y":0.55},{"id":"CM","label":"MC","x":0.5,"y":0.58},{"id":"ML","label":"MG","x":0.25,"y":0.55},{"id":"ST","label":"BU","x":0.5,"y":0.18}]'
);

-- ─── 12. 3-2-2 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '3-2-2',
  '8',
  'Le 3-2-2 est une formation en losange adaptée au football à 8 qui cherche à créer des supériorités offensives grâce à un double attaquant. Avec 3 défenseurs, 2 milieux compacts et 2 attaquants, cette formation vise un équilibre entre solidité et efficacité offensive. Les deux attaquants peuvent se combiner et créer des situations de 2v3 qui perturbent les défenses.',
  'Les 2 milieux jouent très serrés pour protéger les 3 défenseurs et relancer vers les 2 attaquants. En possession, ils cherchent à jouer rapidement pour les deux attaquants qui se combinent en permanence. Les 3 défenseurs restent compacts mais le défenseur central peut monter pour créer des situations de 3v2 au milieu. Les 2 attaquants fonctionnent sur le principe fixateur-mobile : l''un retient les défenseurs, l''autre court dans les espaces.',
  'Pour attaquer contre un 3-2-2, l''espace au milieu est relativement vide avec seulement 2 milieux adverses. Créer un 3v2 au milieu de terrain avec un milieu supplémentaire qui monte peut créer des occasions importantes. Les flancs sont également très ouverts car les 3 défenseurs doivent tous rester dans l''axe, laissant les couloirs libres.',
  'Avec 2 milieux seulement, le milieu de terrain est très compact mais peut être surchargé. La priorité est de garder les 2 milieux proches et disciplinés, ne jamais se laisser attirer vers le haut simultanément. Les 3 défenseurs doivent communiquer clairement pour se répartir les zones de couverture.',
  '["Double attaquant : pression permanente sur la défense adverse", "Milieu compact et difficile à pénétrer en axe", "Nombreuses combinaisons possibles entre les 2 attaquants", "Formation simple à comprendre pour les jeunes joueurs", "Efficace contre les équipes à 1 seul attaquant"]',
  '["Milieu à 2 peut être débordé en infériorité numérique", "Les flancs sont ouverts en défense", "Les 2 attaquants peuvent être coupés du jeu si le milieu est dominé", "Dépend beaucoup de la qualité du duo d''attaquants", "Manque de présence sur les couloirs offensifs"]',
  '["3-3-1", "4-2-1", "3-1-3"]',
  '{"GK": "Gardien actif dans la relance", "CB-C": "Défenseur central : leader défensif", "CB-R": "Défenseur droit", "CB-L": "Défenseur gauche", "CM-R": "Milieu droit : compact, peut monter en soutien des attaquants", "CM-L": "Milieu gauche : récupérateur en priorité", "ST-R": "Attaquant droit : fixateur ou mobile selon la configuration", "ST-L": "Attaquant gauche : complémentaire du partenaire"}',
  '["Catégories jeunes U10-U12 offensives", "Équipes avec 2 bons buteurs", "Football récréatif"]',
  '{"attack": 78, "defense": 65, "pressing": 62, "possession": 68, "transition": 75}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DD","x":0.75,"y":0.8},{"id":"CB-C","label":"DC","x":0.5,"y":0.84},{"id":"CB-L","label":"DG","x":0.25,"y":0.8},{"id":"CM-R","label":"MD","x":0.65,"y":0.55},{"id":"CM-L","label":"MG","x":0.35,"y":0.55},{"id":"ST-R","label":"BU","x":0.65,"y":0.2},{"id":"ST-L","label":"BU","x":0.35,"y":0.2}]'
);

-- ─── 13. 2-3-2 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '2-3-2',
  '8',
  'Le 2-3-2 est la formation la plus offensive du football à 8. Avec seulement 2 défenseurs et un milieu de 3 très haut, elle maximise la présence dans la zone adverse mais s''expose à des contre-attaques dévastatrices. Ce système est idéal pour les équipes dominantes qui cherchent à écraser l''adversaire dès le coup d''envoi, avec une mentalité "on marque plus qu''eux".',
  'Les 3 milieux jouent très haut et créent des situations de supériorité numérique dans la zone de création adverse. Les 2 attaquants restent dans la surface adverse et cherchent les passes décisives des milieux. Les 2 défenseurs doivent être des joueurs d''expérience capables de défendre en 1v1 car ils seront régulièrement en infériorité numérique. Le jeu doit être rapide et vertical pour ne pas laisser l''adversaire s''organiser.',
  'Pour attaquer contre un 2-3-2, l''espace derrière les 3 milieux adverses est immense quand ils sont montés. Une transition rapide sur récupération de balle, avec une passe en profondeur vers un attaquant rapide, crée immédiatement un 2v2 ou 2v1 face aux 2 seuls défenseurs. Les contre-attaques sont la meilleure arme face à ce système.',
  'Défendre contre un 2-3-2 avec seulement 2 défenseurs est le plus grand défi tactique du football à 8. Les 2 défenseurs doivent rester dans leur zone, ne jamais sortir ensemble, et compter sur l''aide des milieux pour revenir défendre. La communication et la couverture mutuelle sont essentielles.',
  '["Présence offensive maximale avec 5 joueurs dans la moitié adverse", "Pression constante sur la défense adverse", "Très difficile à défendre pour les équipes qui ne sont pas préparées", "Football attractif et spectaculaire", "Idéal pour finir les matchs quand on est mené"]',
  '["Défense à 2 très vulnérable aux contre-attaques", "Les 2 défenseurs sont souvent en infériorité numérique", "Formation psychologiquement stressante pour les défenseurs", "Si on concède rapidement, difficile de réorganiser", "Exige une condition physique et une technique très élevées"]',
  '["3-3-1 défensif", "4-2-1", "3-2-2"]',
  '{"GK": "Gardien de haut niveau : doit compenser les failles défensives", "CB-R": "Défenseur droit : expérimenté, calme, fort en 1v1", "CB-L": "Défenseur gauche : idem, communication permanente avec son partenaire", "MR": "Milieu droit : offensif, monte et revient rapidement", "MC": "Milieu central : pivot du jeu, lien entre défense et attaque", "ML": "Milieu gauche : offensif, appels dans la profondeur", "ST-R": "Attaquant droit : finisseur dans la surface", "ST-L": "Attaquant gauche : mobile, fait le travail de fixation"}',
  '["Équipes jeunes très talentueuses", "U13-U15 offensives", "Football récréatif entre amateurs de haut niveau"]',
  '{"attack": 85, "defense": 55, "pressing": 80, "possession": 65, "transition": 82}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DD","x":0.68,"y":0.82},{"id":"CB-L","label":"DG","x":0.32,"y":0.82},{"id":"MR","label":"MD","x":0.78,"y":0.55},{"id":"MC","label":"MC","x":0.5,"y":0.52},{"id":"ML","label":"MG","x":0.22,"y":0.55},{"id":"ST-R","label":"BU","x":0.65,"y":0.2},{"id":"ST-L","label":"BU","x":0.35,"y":0.2}]'
);

-- ─── 14. 4-2-1 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '4-2-1',
  '8',
  'Le 4-2-1 est la formation défensive par excellence du football à 8. Avec 4 défenseurs, 2 milieux compacts et 1 seul attaquant, elle crée un bloc de 6 joueurs derrière le ballon qui est extrêmement difficile à pénétrer. C''est la formation des équipes réalistes qui veulent minimiser les risques et miser sur les phases fixes ou les contre-attaques.',
  'Les 4 défenseurs forment une ligne très compacte qui laisse très peu d''espace entre les lignes. Les 2 milieux couvrent l''espace devant les défenseurs et récupèrent les ballons perdus. L''unique attaquant doit être capable de tenir le ballon seul pendant que les milieux montent en soutien, créant temporairement un 3-2-2 offensif. En phase de possession, le jeu doit être rapide et efficace car l''effectif offensif est réduit.',
  'Le 4-2-1 présente des failles similaires au 5-4-1 en football à 11. L''espace entre le milieu de 2 et la ligne de 4 défenseurs peut être exploité par un meneur de jeu capable de se retourner rapidement. Saturating les flancs avec des joueurs rapides peut étirer la ligne de 4 et créer des espaces dans l''axe.',
  'Le 4-2-1 se défend naturellement très bien grâce à sa ligne de 4 défenseurs. La discipline est primordiale : chaque défenseur doit rester dans sa zone et ne pas se laisser attirer. Le danger principal vient des phases arrêtées adverses.',
  '["Solidité défensive maximale pour le football à 8", "Ligne de 4 défenseurs — très difficile à pénétrer de face", "Idéal pour les équipes en infériorité technique", "Psychologiquement rassurant pour les défenseurs", "Efficace pour tenir un résultat"]',
  '["Un seul attaquant totalement isolé", "Peu de menace offensive — l''adversaire peut défendre haut", "Formation peu attractive à jouer pour les attaquants", "Dépend uniquement des phases arrêtées ou erreurs adverses", "Peut devenir monotone et démotivant pour les joueurs"]',
  '["2-3-2", "3-3-1 offensif", "3-2-2"]',
  '{"GK": "Gardien solide dans les 1v1 — indispensable", "CB-R": "Défenseur droit : fort physiquement", "CB-RC": "Défenseur central droit : axe central sécurisé", "CB-LC": "Défenseur central gauche : leader vocal", "CB-L": "Défenseur gauche : bon dans les duels", "CM-R": "Milieu droit : récupérateur, relance directe", "CM-L": "Milieu gauche : idem, légèrement plus créatif", "ST": "Attaquant : guerrier, capable de tout faire seul pendant 90 minutes"}',
  '["Équipes défensives jeunes", "Football à 8 compétitif — fin de championnat", "Équipes en déplacement contre favorites"]',
  '{"attack": 55, "defense": 85, "pressing": 55, "possession": 58, "transition": 62}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DD","x":0.82,"y":0.8},{"id":"CB-RC","label":"DC","x":0.6,"y":0.83},{"id":"CB-LC","label":"DC","x":0.4,"y":0.83},{"id":"CB-L","label":"DG","x":0.18,"y":0.8},{"id":"CM-R","label":"MD","x":0.65,"y":0.58},{"id":"CM-L","label":"MG","x":0.35,"y":0.58},{"id":"ST","label":"BU","x":0.5,"y":0.2}]'
);

-- ─── 15. 3-1-3 ───────────────────────────────────────────────
INSERT INTO formations (name, type, description, how_to_play, how_to_attack_against, how_to_defend_against, strengths, weaknesses, best_counter_formations, key_player_roles, famous_teams, radar_stats, player_positions)
VALUES (
  '3-1-3',
  '8',
  'Le 3-1-3 est la formation la plus offensive et spectaculaire du football à 8. Avec un seul milieu défensif et un trio offensif haut, cette formation vise à écraser l''adversaire dans sa zone de jeu dès le coup d''envoi. Idéale pour les équipes avec une qualité technique supérieure, elle est risquée mais terriblement efficace quand les joueurs ont le niveau pour la pratiquer.',
  'Le trio offensif reste haut et large pour étirer la défense adverse sur toute la largeur du terrain. Le milieu central unique est le joueur le plus important : il doit à la fois récupérer les ballons perdus, relancer et parfois soutenir l''attaque. Les 3 défenseurs forment une ligne compacte mais haute, permettant à l''équipe de jouer dans la moitié adverse en permanence. En phase de possession, le ballon circule rapidement sur les 3 attaquants pour trouver le déséquilibre.',
  'Pour attaquer un 3-1-3, le milieu adverse est en 1v... plusieurs. Surcharger le milieu adverse unique en créant des 2v1 ou 3v1 crée des transitions rapides vers le but. Les contre-attaques sont également efficaces : avec les 3 attaquants adverses haut et 3 défenseurs dos au but, une transition rapide peut créer une situation 3v3 favorable.',
  'Défendre contre un 3-1-3 nécessite de neutraliser le milieu adverse unique. Si on l''isole et qu''on récupère le ballon dans la zone médiane, des contre-attaques à 3 ou 4 contre 3 adverses sont possibles. La clé est d''être discipliné défensivement et d''attendre les opportunités de récupération.',
  '["Formation ultra-offensive — pression permanente sur la défense", "Trio offensif très difficile à défendre pour une défense à 3", "Football spectaculaire et attractif", "Idéale pour les équipes très techniques", "Psychologiquement dominante — l''adversaire subit"]',
  '["Le milieu seul peut être débordé en 3v1 facilement", "Défense à 3 vulnérable aux transitions rapides", "Formation très risquée si le milieu unique est éliminé", "Exige un trio offensif de très haute qualité", "Difficile à pratiquer sur terrain humide ou terrain réduit"]',
  '["3-3-1 (compact)", "4-2-1", "3-2-2"]',
  '{"GK": "Gardien de haut niveau — dernier rempart sur de nombreuses contre-attaques", "CB-R": "Défenseur droit : fort en 1v1, prend des risques mesurés", "CB-C": "Défenseur central : libero vocal et expérimenté", "CB-L": "Défenseur gauche : couverture côté gauche", "CM": "LE milieu — le joueur le plus important : athlète complet, récupérateur et distributeur", "RW": "Ailier droit : vitesse, dribble, finition", "CF": "Avant-centre : pivot, combine avec les ailiers, finisseur", "LW": "Ailier gauche : percussion, rentre dans l''axe pour frapper"}',
  '["Équipes U13-U15 très techniques", "Académies de football formateur", "Football récréatif offensive entre amis"]',
  '{"attack": 90, "defense": 52, "pressing": 85, "possession": 62, "transition": 85}',
  '[{"id":"GK","label":"GB","x":0.5,"y":0.95},{"id":"CB-R","label":"DD","x":0.72,"y":0.82},{"id":"CB-C","label":"DC","x":0.5,"y":0.85},{"id":"CB-L","label":"DG","x":0.28,"y":0.82},{"id":"CM","label":"MC","x":0.5,"y":0.58},{"id":"RW","label":"AD","x":0.8,"y":0.22},{"id":"CF","label":"BU","x":0.5,"y":0.15},{"id":"LW","label":"AG","x":0.2,"y":0.22}]'
);
